### PR TITLE
——

### PR DESCRIPTION
**Pull request by AnnikenYT**
Hi there, I solved task 1 using nodejs and cryptojs, and since I don’t really need the Amazon card since im under 18, I thought id give others a little hint. The code should work by just running the main.ja with node after installing the workspace. Not gonna describe how that works tho, i dont want to make it too easy to just copy and paste without knowing at least a bit about JS development ;)

### CODE REVIEW

**Comment by Intevel** [comment]
Solved Task 1 too.

**Comment by Intevel** [comment]
But I dont think you have to open a PR for that. It's challenge

**Comment by Intevel** [comment]
I just solved it in the Developer Tools console, even if you figure out the gift card completely and don't need it just let others redeem it. **Good work!**  I love challenges like that

**Comment by AnnikenYT** [comment]
Yea i was on my ipad so i couldn't use devtools (dang you, safari!)

**Comment by AnnikenYT** [comment]
> But I dont think you have to open a PR for that. It's challenge

Yea we'll see maybe i'll delete it again, just thought it might be helpful to people who are new to js and just interested in how to solve it

**Comment by Intevel** [comment]
Yes only your PR is public, that's stupid. Make it after the challenge, so others get the solution while some sat down there and try to solve it.

**Comment by AnnikenYT** [comment]
Well, turns out you can’t actually delete a pr.
But since the next part of the challenge will start today i don’t think that this is too relevant anymore :)

**Comment by JonathanSchndr** [comment]
Of course, PR is not so good, but I think the idea is great that others can see how you solved it. Next time just think of a gitignore for node modules 😊

**Comment by Intevel** [comment]
Yes it is a good idea but as I said I don't think it makes much sense as long as the challenge is still running.

**Comment by JonathanSchndr** [comment]
Yes! I also don’t understand why you still can’t deactivate PR 😐

**Comment by AnnikenYT** [comment]
Yep, forgot that 😅

**Comment by AnnikenYT** [comment]
> Yes! I also don’t understand why you still can’t deactivate PR 😐

Yeah, in general not being able to remove prs and issues is quite bad imo.
I mean, I guess it's part of the philosophy, that you shouldn't hide any errors or something during development, but when you do something dumb like me and make a pull request too early it would be useful

**Comment by JonathanSchndr** [comment]
No problem mate. 👍

**Pull request closed without merging**
